language: clojure
sudo: false
jdk:
  - openjdk14

services:
  - docker

cache:
  directories:
  - /home/travis/.m2
  - !home/travis/.m2/repository/spacetools

env:
  global:
    - DEV_WS="${TRAVIS_BUILD_DIR}/environments/development"

install:
  - cd $DEV_WS && lein deps

script:
  # Build Spacetools
  - cd $TRAVIS_BUILD_DIR && lein polylith build -test
  # Testing files
  - cd $DEV_WS && lein cloverage --codecov

before_deploy:
  - cd "${TRAVIS_BUILD_DIR}"
  - docker build -f Dockerfile         -t jare/spacetools:latest  .
  - docker build -f Dockerfile.noemacs -t jare/spacetools:noemacs .

deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/travis/deploy
  on:
    branch: master
