language: clojure
sudo: false
jdk:
- openjdk11

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install emacs-25.1-travis --use --skip

install:
  - cd "${TRAVIS_BUILD_DIR}/scripts/sdnize" && cask install

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - lein polylith build -test
  - cd "${TRAVIS_BUILD_DIR}/environments/development"
  - lein cloverage -o cov --coveralls
  - lein exec -p scripts/coveralls/fix-paths.clj "${TRAVIS_BUILD_DIR}" cov/coveralls.json
  - curl -F 'json_file=@cov/coveralls.json' https://coveralls.io/api/v1/jobs
  - cd "${TRAVIS_BUILD_DIR}/scripts/sdnize" && cask exec ert-runner
