language: clojure
sudo: false
jdk:
  - openjdk14

services:
  - docker

cache:
  directories:
  - /home/travis/.m2

env:
  global:
    - CLJ_WS="${TRAVIS_BUILD_DIR}/environments/development"

install:
  - cd $CLJ_WS && lein deps

script:
  # Build Spacetools
  - cd $TRAVIS_BUILD_DIR && lein polylith build -test
  # Testing files
  - cd $CLJ_WS && lein cloverage --codecov

# Upload coverage reports to codecov.io
after_success:
  - cd "${TRAVIS_BUILD_DIR}"
  - curl -fsSL https://codecov.io/bash -o codecov.bash
  - bash ./codecov.bash
  
before_deploy:
  - docker build -f Dockerfile         -t jare/spacetools:latest  .
  - docker build -f Dockerfile.noemacs -t jare/spacetools:noemacs .

deploy:
  provider: script
  script: bash scripts/travis/docker_push
  on:
    branch: master
